### ISSUE TITLE
About the future of 'home-assistant-sun-card' via this fork

### ISSUE THREAD

**Issue by ThomDietrich** [rejuvenate/lovelace-horizon-card#1]
Hey all,
looking forward to continue the development of home-assistant-sun-card in this repository.
https://github.com/AitorDB/home-assistant-sun-card/issues/164

Let's discuss first steps.

1. Add some context about this fork to the README file
2. Create PRs for the PRs currently open in the original repository
3. Merge all translation PRs from the original repository
4. Publish this repository to HACS

**Comment by selfish** [comment]
Hi @ThomDietrich,

I appreciate your proposal and find it to be well-thought-out. Regarding point (2), I recommend creating issues and inviting the original contributors to resubmit their PRs against our fork. This approach will not only increase awareness of our fork as the lead for the old repo but also foster collaboration among contributors.

Additionally, I suggest prioritizing the publication of this repository to HACS, given the evident demand. To comply with naming conventions for cards, we may need to adjust the repository name to `lovelace-sun-card`. This change will ensure consistency and improve discoverability within the HACS ecosystem.

If you agree with these suggestions, let's proceed with renaming the repo and implementing the proposed changes.

**Comment by avataar** [comment]
Inviting the original contributors sounds like a great idea. Let's go with the rename and push it to HACS!

**Comment by selfish** [comment]
Awesome, on it.
Thank you!

**Comment by selfish** [comment]
Oh, it looks like we have rather limited access to the repo settings.
@ThomDietrich could you please help us rename the repo to `lovelace-sun-card` so we can go ahead and re-submit it to HACS?
Thanks!

**Comment by ThomDietrich** [comment]
Hey both,
bare with me. Why do we need lovelace in the name? The name is discouraged and the majority of popular repos follows the `sun_card` schema: https://github.com/topics/lovelace-card

**Comment by ThomDietrich** [comment]
> Inviting the original contributors to resubmit their PRs against our fork. 

I agree with this for feature PRs as well as for users which raised interesting issues in the past.
I would make an exception regarding the translations. They are rather small and were one-shot contributions. I suggest to simply cross-merge these PRs directly into a branch and open a PR for public discussion. This will not break the git authors and we can ask all original contributors for feedback. Wdyt?

**Comment by selfish** [comment]
> Could you point me to the HACS recommendations you are talking about?

After looking up where I read that, I realized I was initially mistaken about HACS' naming requirements. While it's true that they recommend the `lovelace-card-name` convention for cards, it's not a strict rule, and they do allow for other naming patterns, especially in the case of legacy repos.

However, I believe that adopting the `lovelace-card-name` convention would be a beneficial move for our project. This naming pattern is recognizable and trusted within the Home Assistant community. By following this convention, our repo's name would be easily identifiable and could potentially lead to greater adoption and trust among users.

I think it's worth considering, given the potential benefits. I'd love to hear your thoughts on this and whether you'd be open to making the change.

Thanks for considering, and I'm looking forward to hearing your opinions!

**Comment by ThomDietrich** [comment]
Next steps:

1. Merge #4
1. Merge develop branch
1. Test component
1. Release first rejuvenate version on GitHub
1. Publish to HACS (see for context: https://github.com/hacs/default/commit/7d67da34b84e73542ea994f26a2ba0388aad7f33)
1. Invite contributors
1. Innovate
1. ...
1. Profit!

**Comment by ThomDietrich** [comment]
Hey guys,
I think it would be important to publish a new release and register with HACS default repo asap.

These are the steps:

- [ ] Resolve conflicts and merge #4 @selfish (let's get this finished, even though it's not strictly needed for the release)
- [ ] Agree on project name, see #11 @selfish @avataar 
- [ ] Build a testing release, test locally
- [ ] Publish Github Release "v0.2.0" 
- [ ] Publish to HACS: https://hacs.xyz/docs/publish/include/

**Comment by tjorim** [comment]
Lovelace was more of a project name, it's not the 'official' name (anymore).
The HA repo is renamed to frontend and all other documentation talks about Dashboards.

**Comment by ThomDietrich** [comment]
@edwardtfn regarding your question in #4, the list above shows what needs to happen next.

**Comment by kquinsland** [comment]
I just wanted to say THANK YOU for picking this up. The repo / new releases are already in HACS and it was maybe 20 seconds for me to re-add it and adjust my dashboards. Couldn't have been simpler and for that I am grateful. Not all project re-incarnations go so smoothly!

**Comment by edwardtfn** [comment]
I've added comments on #21 about minor differences when compared to the original card (which migrating users will do) but I think it's time to wrap up and request inclusion to HACS default directory.

**Comment by ThomDietrich** [comment]
@edwardtfn Didn't start before the rename to "horizon-card" was settled. Now it is time (!) and please go ahead, we are all equals here!

**Comment by ThomDietrich** [comment]
@edwardtfn of course let us know if you need any further input to publish the project to HACS :)

**Comment by edwardtfn** [comment]
Done!

https://github.com/hacs/default/pull/1808

**Comment by gpongelli** [comment]
waiting for this fork being available in HACS 😉

**Comment by edwardtfn** [comment]
Another good news: https://github.com/hacs/default/pull/1808

The PR was merged!

**Comment by edwardtfn** [comment]
Th PR to add into HACS default repository was rejected. 😩
https://github.com/hacs/default/pull/1808

**Comment by ThomDietrich** [comment]
This is devastating. Sorry @edwardtfn, three months for nothing. 

New PR: https://github.com/hacs/default/pull/1958 (please check for any errors 🙃)

**Comment by khenderick** [comment]
I noticed that you had reverted an end-of-file newline change, but it looks like there's still an end-of-file newline change on the PR. Maybe it's best to revert that so it doesn't get closed if no such newline is allowed :thinking: .

**Comment by ThomDietrich** [comment]
Thanks @khenderick! The newline was introduced by the GitHub online editor (which I used for this simple addition. It's bad practice to not have newline at the end of this file but anyhooow, I've fixed it. Thanks for your review

**Comment by ThomDietrich** [comment]
Just remembered, wdyt? Should we make this change? https://github.com/rejuvenate/lovelace-horizon-card/issues/52#issuecomment-1564459807

**Comment by avataar** [comment]
It's really disappointing to see the HACS addition declined, especially having to wait that long for something that shouldn't take more than a day. Hopefully we'll have more luck now.

**Comment by edwardtfn** [comment]
It was merged!!!
https://github.com/hacs/default/pull/1958

**Comment by ThomDietrich** [comment]
Finally!
