### ISSUE TITLE
Incorrect moon phase being displayed

### ISSUE THREAD

**Issue by kaizersoje** [rejuvenate/lovelace-horizon-card#103]
I noticed that the wrong moon phase is being displayed in the card

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/54566217/9f4a0cf4-466f-4f73-846d-3767c880be6d)

The state of the `sensor.moon` on this day was actually `waning_gibbous`

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/54566217/4ff15fb2-29a3-4742-be2e-1af18a00be78)

**Comment by Speedymatze** [comment]
This also manifests itself in my case. The language settings are set to German everywhere.
<img width="935" alt="Screenshot 2024-01-03 130128" src="https://github.com/rejuvenate/lovelace-horizon-card/assets/95613753/07bb3032-817d-4194-88f5-25fa5644aa06">

**Comment by brebtatv** [comment]
Same problem in the Czech language.
![horizon card](https://github.com/rejuvenate/lovelace-horizon-card/assets/10747062/63c0ca09-a0fa-4f6f-9a46-3e468a7d2603)

**Comment by kaizersoje** [comment]
The issue is still there.

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/54566217/d8a2d83c-19d7-4450-8ae1-e949edf12171)
![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/54566217/7dde9939-97f0-4fad-b7f8-ca6d7efa40f4)

I have pasted the moon phase for my location from timeanddate.com as well.

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/54566217/55d0fcbe-45a6-4665-93ac-789789b61328)

**Comment by wgumaa** [comment]
I am also getting this issue! All language is in english but displaying "full_moon!" when my moon entity is showing "Waning gibbous "

**Comment by ThomDietrich** [comment]
Hey guys, this issue was resolved in #134 and you may upgrade to v1.1.0 :)
