### ISSUE TITLE
No add card option in Lovelace

### ISSUE THREAD

**Issue by RCarlsonMD** [rejuvenate/lovelace-horizon-card#106]
Trying to add lovelace-horizon-card, but no "add card" option is displayed in the Lovelace hamburger menu after downloading it. Only "edit dashboard" is displayed. No "add card"  

HACS is installed, and the lovelace-horizon file downloaded, but no option to "add card" from Lovelace, even after restart. 

What am I missing? 

Thanks!

**Comment by ildar170975** [comment]
The "add card" is displayed only when a dashboard is in edit mode.
To switch a dashboard to the edit mode - select "edit dashboard".

**Comment by ThomDietrich** [comment]
Thanks @ildar170975.
@RCarlsonMD  Feel free to comment again if you can't find it!

<img width="993" alt="image" src="https://github.com/rejuvenate/lovelace-horizon-card/assets/2870104/add0be5f-7c92-49dd-88fa-cf28ba522f42">

**Comment by ildar170975** [comment]
@RCarlsonMD 
1. This question is absolutely not related to this particular custom card. Suggest to ask similar questions in HA Community: https://community.home-assistant.io/c/configuration/frontend/33
2. In short. you seem to be using an auto-generated dashboard; you cannot add cards to this dashboard. Details - in [Docs](https://www.home-assistant.io/dashboards/).

**Comment by RCarlsonMD** [comment]
The menu under edit dashboard shows: 

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/20015395/9ba80f9b-9376-410d-9c86-e5a6126e0a76)

I don't want to go down the "take control" rathole, if possible. I simply want to add a card to Lovelace.
