### ISSUE TITLE
moon support

### ISSUE THREAD

**Issue by leonardpitzu** [rejuvenate/lovelace-horizon-card#11]
How about adding support for the moon?

**Comment by ThomDietrich** [comment]
Previously discussed in https://github.com/AitorDB/home-assistant-sun-card/issues/144

**Comment by selfish** [comment]
That's an interesting idea; let's investigate it. I can look into it next week. After a quick glance at the `moon` integration, it doesn't seem to provide rise/set times; only the moon phase. How could we support the moon's position? Any ideas?

**Comment by Tom-ahawk** [comment]
Using the AstroWeather integration you will get these sensors:

![image](https://user-images.githubusercontent.com/35527507/226129571-049bb693-3a53-41ca-91a2-a20270a52964.png)

**Comment by leonardpitzu** [comment]
You can use this:Broham/suncalcPy: A python implementation of the SunCalc javascript library.github.com Ormourner/suncalc: A tiny JavaScript library for calculating sun/moon positions and phases.github.comOn 18 Mar 2023, at 20:39, Tom-ahawk ***@***.***> wrote:﻿
Using the AstroWeather integration you will get these sensors:

**Comment by JasringStw** [comment]
I would love to see the moon in the same card with a different color. looking forward to see your developments on this.

**Comment by selfish** [comment]
@ThomDietrich @avataar there are several options here and I think we can add optional support for the moon. I'd love to see this too. I think we can go ahead with the rename.

**Comment by avataar** [comment]
It's a good idea but let's not jump ahead with renaming things just yet. I'd first like to see the project stable and released before we decide on the bright future :)

**Comment by ThomDietrich** [comment]
All, please hold your horses :) 

@avataar @selfish the only thing we need to discuss and decide ASAP is, whether we want to rename the project BEFORE publishing to HACS. Options:

1. "Sun Card" - the name many are used to from the parent project. I believe it wouldn't be totally illogical to add moon support, ISS support, Jupiter support, ... but it will surprise new users. 
2. "Sun Moon Card" or similar - The name includes "Moon", but is limited to it. I honestly wonder if anyone is interested in other celestial objects?
3. "Astrology Card", "Sky Card" or similar - Anticipate sun, moon, X support. I am not in favor of ditching the known "Sun Card" name

**Comment by tjorim** [comment]
I was thinking of other stuff that also could refer to more than just the sun:

- dashboard-daybreak-card
- dashboard-horizon-card
- dashboard-atmosphere-card
- dashboard-sky-card
- dashboard-star-card

**Comment by avataar** [comment]
> 1. "Sun Card" - the name many are used to from the parent project. I believe it wouldn't be totally illogical to add moon support, ISS support, Jupiter support, ... but it will surprise new users.

Since this is what the card currently does, it's the most fitting and it's a drop in replacement for the original project, i.e. having "custom:sun-card" in your existing dashboard will continue to work.

> 2. "Sun Moon Card" or similar - The name includes "Moon", but is limited to it. I honestly wonder if anyone is interested in other celestial objects?

Since we still don't have moon support, the name doesn't fit. I don't believe other celestial objects are needed either.

> 3. "Astrology Card", "Sky Card", "Sun+X Card" or similar - Anticipate sun, and all further support. I am not in favor of ditching the known "Sun Card" name but happy to hear name suggestions.

"Sky Card" is a good fit if we really want to reserve the opportunity to add something other than the Sun in the future.

"Horizon Card" (based on @tjorim's suggestions) sounds good too.

Regarding the name of the repository, I think "lovelace-xxx-card" is better than "dashboard-xxx-card" as "lovelace" is a very specific term that refers to HA unambiguously while "dashboard" is very generic, but I have no strong opinion on that one.

**Comment by JasringStw** [comment]
I love the horizon-card option, leaves all options open for further developments.

**Comment by ThomDietrich** [comment]
The name `lovelace-horizon-card` is certainly quite neat. 

Let's have the community decide:

- React with 🎉 if you support the name `lovelace-horizon-card` -> "Horizon Card"
- React with 🚀 if you prefer to stay with the established name `lovelace-sun-card` -> "Sun Card", while we would still add moon support, which would be slightly illogical but not a dealbreaker

**Comment by edwardtfn** [comment]
"Sky card" would have my vote. 😜
Or "Astro card".

**Comment by ThomDietrich** [comment]
@edwardtfn you caught me off guard there. I feel ashamed that I've mixed terms known from clown culture and science 🙈

The majority has spoken :) We have a winner.

**Comment by lcnittl** [comment]
Nooo  -- I tuned in too late! Would have voted for `lovelace-luminary-card` or `lovelace-luminaries-card`.

**Comment by ThomDietrich** [comment]
@lcnittl care to elaborate? :-) https://dictionary.cambridge.org/de/worterbuch/englisch/luminary

**Comment by lcnittl** [comment]
@ThomDietrich absolutely!

It is a (slightly older, probably) term for (shining) celestial/heavenly bodies.

<sub>From https://en.wikipedia.org/wiki/Luminary</sub>
> **Luminary**
> _A [celestial body](https://en.wikipedia.org/wiki/Celestial_body), as the [sun](https://en.wikipedia.org/wiki/Sun) or [moon](https://en.wikipedia.org/wiki/Moon) or an object that gives [light](https://en.wikipedia.org/wiki/Light); or, a person of eminence or brilliant achievement. From [Old French](https://en.wikipedia.org/wiki/Old_French) luminarie or late [Latin](https://en.wikipedia.org/wiki/Latin) luminarium, from [Latin](https://en.wikipedia.org/wiki/Latin) lumen, lumin- "light"._

<sub>From https://en.wiktionary.org/wiki/luminary#Noun</sub>
> **luminary** (plural [luminaries](https://en.wiktionary.org/wiki/luminaries#English))
> [...]
> 2) ([archaic](https://en.wiktionary.org/wiki/Appendix:Glossary#archaic)) A [body](https://en.wiktionary.org/wiki/body) that [gives](https://en.wiktionary.org/wiki/give#Verb) [light](https://en.wiktionary.org/wiki/light#Noun); especially, one of the [heavenly bodies](https://en.wiktionary.org/wiki/heavenly_body).
> [...]

So a nice collective term for both sun and moon (and others).

**Comment by jazzyisj** [comment]
Love the idea of moon support.  I currently stack my horizon card with an entities card with a moon phase template entity that has a dynamic image icon for the moon phase.  It would be cool to see something like this integrated right into the horizon card.


<img width="315" alt="image" src="https://user-images.githubusercontent.com/44064559/229310722-f9f8d13c-c792-422a-8497-f014e7e4daa7.png">

**Comment by avataar** [comment]
Here is a preview of the upcoming Moon support (different locations and times):

![screencapture-localhost-8123-new-horizon-default-view-2023-04-16-21_32_30](https://user-images.githubusercontent.com/4996703/232436865-6ed87c4d-7313-4088-a869-96276b6e3d4d.png)

What is the new Moon stuff:
- Showing the Moon as it moves above and below the horizon visually matching what you'd see at your location/time
- Support for showing the azimuth and elevation - I believe it's best if shown together with those of the Sun, with the appropriate astronomical symbols. If only the azimuth/elevation of one of the bodies is configured to be shown, no symbol will be displayed.
- Support for showing moonrise, moonset and moon phase. The phase will be rotated to approximately match your latitude but that can be overridden via config option.

This is how it looks with different fields shown/hidden:

![screencapture-localhost-8123-horizon-options-default-view-2023-04-16-21_44_19](https://user-images.githubusercontent.com/4996703/232438208-d88254ff-db7c-4832-93cf-cbef3b707ea5.png)

There are other non-moon related changes, see #40 for details.

**Comment by edwardtfn** [comment]
> A [celestial body](https://en.wikipedia.org/wiki/Celestial_body), as the [sun](https://en.wikipedia.org/wiki/Sun) or [moon](https://en.wikipedia.org/wiki/Moon) or an object that gives [light](https://en.wikipedia.org/wiki/Light);

It's a bit questionable call the Moon as an object that "gives light", no? 😜
If you say the Moon gives light you have to say that any visible object gives light.

**Comment by avataar** [comment]
Last teaser but I just had to share. It feels really good when the Moon is exactly where the Horizon card says it should be :) Local time 2:17.

![moon-horizon](https://github.com/rejuvenate/lovelace-horizon-card/assets/4996703/84e4591a-5bb3-445c-baf1-e6c939927192)

Coming out soon!
