### ISSUE TITLE
no translation into Italian of the moon phases but the English name remains followed by (!)

### ISSUE THREAD

**Issue by Diegocampy** [rejuvenate/lovelace-horizon-card#125]
I inserted the card and the English translation only works for the sun, not the moon. The moon integration however works perfectly if I look at it from the settings outside of this card

**Comment by ThomDietrich** [comment]
Hello and thanks for reporting this issue!
This is a bug introduced with HA 2024.04, already reported in https://github.com/rejuvenate/lovelace-horizon-card/issues/122 We are looking for willing developers to provide a bug fix PR.
