### ISSUE TITLE
Started showing code instead of state on moon

### ISSUE THREAD

**Issue by 715Steve** [rejuvenate/lovelace-horizon-card#129]
Even though Moon integration is installed in HA the moon phase has started showing waning_gibbuous (!) etc. This started after a recent HA update.
I have removed and reinstalled both the Moon integration and this card but the problem persists.

**Comment by ThomDietrich** [comment]
Hello @715Steve thanks for reporting the issue! We already have a solution in the pipeline. We will release the fix soon!

https://github.com/rejuvenate/lovelace-horizon-card/issues/122

**Comment by DHLF** [comment]
Same on my side. Sad.

A quick look at the integration "moon" showed there is only ONE parameter given, the "state" of the moon(full/half/hollow, err..)
Did the other parameters gone missing after the update??
