### ISSUE TITLE
No connection to moon-integration

### ISSUE THREAD

**Issue by TobiasPatzel** [rejuvenate/lovelace-horizon-card#130]
Hi, the moon phase displays a ‘!’ after the name even though the moon-integration is installed.

The horizon-card gets the information automatically from the moon-integration, or do I need to link something there?

![Horizon Card](https://github.com/rejuvenate/lovelace-horizon-card/assets/74508083/a2ba7456-f1e7-432e-a87e-5a0eeaa1df35)

**Comment by wgumaa** [comment]
I am also getting this issue! All language is in english but displaying "full_moon!" when my moon entity is showing "Waning gibbous "

**Comment by jm314159** [comment]
Duplicated issue. Please follow the solution in #122

**Comment by TobiasPatzel** [comment]
Sorry, I didn't see that. Many thanks for the info.
