### ISSUE TITLE
Text for moon phase

### ISSUE THREAD

**Issue by marioth1** [rejuvenate/lovelace-horizon-card#133]
Hello, on my HA the text for moonphase is displayed strange (with underscore and exclamation mark). I believe to remember this was not always the case,

br
Mario
![IMG_5977](https://github.com/rejuvenate/lovelace-horizon-card/assets/121566075/909c3f95-3c7e-4463-b9e3-c0195d872d90)

**Comment by tripplehelix** [comment]
I also have this issue, even with `moon:` in configuration.yaml and the moon integration installed via GUI.
