### ISSUE TITLE
Feature Request: Add Terrain Support for Sunrise/Sunset Calculations in Horizon Card

### ISSUE THREAD

**Issue by ShivaSVK** [rejuvenate/lovelace-horizon-card#146]
Context: I live in a valley surrounded by steep hills that significantly affect the visibility of sunrise and sunset from my location. While the standard sunrise/sunset times in Home Assistant (HA) are accurate for flat terrain, the local topography alters these times due to obstructing terrain.

Request: Could you add support for considering the surrounding terrain in the Lovelace Horizon Card? Specifically, it would be helpful if users could specify terrain data that adjusts the sunrise/sunset calculations based on local topography.

Potential Solution: One potential approach could be to allow users to import terrain data in a simple format, such as CSV, to account for the local horizon. For example, terrain data can be downloaded from tools like [PVGIS](https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html), which provides CSV exports for terrain profiles.

Implementation Idea:

Enable users to paste or upload CSV data with elevation angles for different azimuths (terrain profile).
Use this data to adjust the calculated horizon line, affecting the displayed sunrise and sunset times.
Perhaps a basic interface or helper could allow users to input or visualize their terrain profiles directly within HA.
Benefits: This feature would make the sunrise/sunset times much more accurate for people in hilly or mountainous regions, providing more realistic data for automations and displays.

Thanks for considering this request!

**Comment by ThomDietrich** [comment]
Hello @ShivaSVK, this is a very interesting suggestion.
I can see this being implemented as a feature, however not initially in the horizon-card. Consider that the card primarily presents the information visually. I think what you are looking for is an improvement in the `sun` or `sun2` component. I suggest to copy&paste your idea there!
As soon as this is implemented there, we would be more than happy to accept this feature for the horion card :)

**Comment by ShivaSVK** [comment]
Than you for suggestion. Made a Feature request on HA community page:
https://community.home-assistant.io/t/add-terrain-support-for-sunrise-sunset-calculations/767898
