### ISSUE TITLE
can't install card

### ISSUE THREAD

**Issue by pesmi30** [rejuvenate/lovelace-horizon-card#148]
When I click on the supplied (HACS) link, I get

Repository rejuvenate/lovelace-horizon-card not found

**Comment by ThomDietrich** [comment]
Hello,
could it be that there was a mistake when you copied the link? Maybe the URL in your system is indeed invalid. Please remove and add again. If the issue persists please come back here

**Comment by pesmi30** [comment]
Hello Thomas,

 

I can’t imagine that I could have done something wrong with a simple click…

But I can’t reproduce it…

 

When the problem occurred last week, I solved it by installing the card manually (download to www and so on).

So it works fine.

 

It’s a little pitty that the names of the moonphases are not localized (I live in the Netherlands).
Maybe I’ll change the literals in the js-module…

 

 

Regards,

Peter

 

Van: Thomas Dietrich ***@***.***> 
Verzonden: vrijdag 25 oktober 2024 09:22
Aan: rejuvenate/lovelace-horizon-card ***@***.***>
CC: pesmi30 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rejuvenate/lovelace-horizon-card] can't install card (Issue #148)

 

Hello,
could it be that there was a mistake when you copied the link? Maybe the URL in your system is indeed invalid. Please remove and add again. If the issue persists please come back here
