### ISSUE TITLE
Visual differences when compared to the original card

### ISSUE THREAD

**Issue by edwardtfn** [rejuvenate/lovelace-horizon-card#21]
If you compare the new card (bottom) to the original one (top) when added with standard settings (no additional configuration other than adding the card) there are some visual differences:

![image](https://user-images.githubusercontent.com/94725493/227111758-ef9e84c4-4e47-47cd-88bc-1d8fe84bd486.png)

- Azimuth and elevation showing as default in the new card.
  This will be seen as a breaking change for users migrating from the previous card, so I think we should set those two keys to be `false` as default.

- The position of sunset & sunrise has changed.
  I think this was an improvement.

- The font color used to the key names are different.
  I think this is minor and we should wait for feedback from users before spending time on this.

- The font size used to the key names are different.
  It looks a bit packed now. Is this just me feeling this?

**Comment by ThomDietrich** [comment]
Hey @edwardtfn,
I agree with all your points, great initiative comparing old and new.

> Azimuth and elevation showing as default in the new card. [...] set those two keys to be false as default.

Yup, these shouldn't be forced as defaults. Would you like to create a PR?

> The font size used to the key names are different. It looks a bit packed now. Is this just me feeling this?

Nope. While most of the new styling is pleasing to my eyes, I am thrown off by the position of the sunrise/sunset times, which looking at the css definitions is an error, as all numbers are crammed in a 20px line. This fixes the issue:

```css
.horizon-card-header .horizon-card-field-value {
	font-size: 1.85rem;
	line-height: 28px;
}
```

Addition:

*  Azimuth and elevation should have a unit (`x °`)

**Comment by avataar** [comment]
Yes, I'm aware of those and was just about to open an issue :)

The differences stem from the fact that the latest version of the original card didn't include all changes from the develop branch of the original repository and our fork does. I will compare it to other cards/best practices to see how we can manage font sizes and styles better.

I'm looking into the azimuth/elevation thing too - they are off by default and it seems none of the keys that configure what should be shown do anything (i.e. you can't hide azimuth/elevation at all).

**Comment by Gferretta** [comment]
Hello
Thank you for taking back this great card.

I've noticed that only sunrise and sunset work for true/false values.
I leave attached screen.

Regards

![card](https://user-images.githubusercontent.com/65413059/227245648-fb96b55e-bdc0-453c-85a9-4da6db4f71c9.jpg)

**Comment by avataar** [comment]
Please have a look at the above PR - lots of screenshots.

**Comment by ThomDietrich** [comment]
That looks really nice @avataar !!

**Comment by avataar** [comment]
All of the above are resolved now.
