### ISSUE TITLE
HACS (no Issue)

### ISSUE THREAD

**Issue by whyisthisbroken** [rejuvenate/lovelace-horizon-card#29]
Hey, maybe i´m completly stupid but the description says "Lovelace Horizon Card" is on HACS - but where ? I dont find it ?
Not under SunCard or Lovelace Horizon Card...

**Comment by chatainsim** [comment]
Hello, I was unable to find it too so I've added it in the custom repo in HACS.

**Comment by erkr** [comment]
Same question, I guess it's being prepared for first lauch

**Comment by avataar** [comment]
It's still not on the HACS default repos list (but will be soon). For the time being you need to add it as a custom repo in HACS.

**Comment by whyisthisbroken** [comment]
Thank you - maybe you should remove then the installation via HACS if it not available for now. :) Thanks for the Info.

**Comment by ThomDietrich** [comment]
@whyisthisbroken check the new README in my open PR :)
