### ISSUE TITLE
Horizon-card customize with card-mod.

### ISSUE THREAD

**Issue by WarC0zes** [rejuvenate/lovelace-horizon-card#30]
Hi,
Already, a big thank you for taking over the sun-card project.

I use sun-card and I customized the font with card-mod to be able to display well with 2 cards side by side.
![Sun-card customize](https://user-images.githubusercontent.com/91471397/227754338-98477bae-298b-4514-9a2a-9d9fc549cf67.png)
code:
```
              - type: custom:sun-card
                showAzimuth: true
                showElevation: true
                card_mod:
                  style: |
                    .sun-card-footer .sun-card-text-subtitle {
                        font-size: 0.91rem !important;
                        color: var(--primary-text-color) !important;
                    }
                    .sun-card-header .sun-card-text-subtitle {
                        font-size: 0.91rem  !important;
                        color: var(--primary-text-color) !important;
                    }
                    .sun-card-header .sun-card-text-time {
                        font-size: 0.8rem  !important;
                        color: var(--primary-text-color) !important;
                    }
                    .sun-card-footer .sun-card-text-time {
                        font-size: 0.8rem  !important;
                        color: var(--primary-text-color) !important;
                    }
                    ha-card > div > div.sun-card-body {
                      padding-top: 0;
                    }
                    ha-card > div > div.sun-card-footer > div:nth-child(1) {
                      padding-top: 0;
                    }
                    ha-card > div > div.sun-card-footer > div:nth-child(2) {
                      padding-top: 0.5rem;
                    }               
```
with Horizon-card by default:
![horizon](https://user-images.githubusercontent.com/91471397/227760563-84fc0b56-3021-4409-9380-0472ddcbbc3e.png)

I want to do the same with horizon-card, but it's impossible. When I modify the code with the editor it works and when I save it comes back to the default values.
![Horizon-card customize edit](https://user-images.githubusercontent.com/91471397/227754592-eec7d7cf-7479-42e8-8432-91216fda5ecf.png)

code:
```
type: custom:horizon-card
fields:
  azimuth: true
  dawn: true
  dusk: true
  elevation: true
  noon: true
  sunrise: true
  sunset: true
card_mod:
  style: |
    ha-card > div > div.horizon-card-header > div:nth-child(1) >
    span.horizon-card-field-name {
      font-size: 1rem !important;
    }
    ha-card > div > div.horizon-card-header > div:nth-child(2) >
    span.horizon-card-field-name {
      font-size: 1rem !important;
    }
```

after save:
![Horizon-card customize edit2](https://user-images.githubusercontent.com/91471397/227754692-e595ba37-f0ee-4066-aed1-5b19fd344785.png)

Can you make the modifications possible with card-mod or do you have a workaround?

**Comment by captSL** [comment]
Same for me. I'm not able to apply any styling with `card-mod` to this.

**Comment by avataar** [comment]
I'm not sure why it happens but as part of the major changes I'm working on I also reworked the css and it seems to work with card-mod. So while I can't offer you a fix right now it will work in the very near future.

**Comment by WarC0zes** [comment]
@avataar
Thank you for this information, I will wait for a next release.

**Comment by ildar170975** [comment]
card-mod style does not stick.
Consider this small (and useless styling):

![изображение](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/8fe458ad-ebc2-4fda-bbcb-ad328228b9b2)

The `color: red` is applied - check in Code Inspector.
Then save the car, check with Code Inspector - the style is lost.
Reopen the Editor - still lost:

![изображение](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/233e565b-2321-4db7-a48a-64811f9d115d)

Type a "whitespace" somewhere - the style is here again:

![изображение](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/a18526d1-2dbc-43c5-a5a5-bcbed6e53f3c)

**Comment by avataar** [comment]
I just opened the above PR that coincidentally should also fix this issue. If you could give a try, I'd appreciate it. You can either build a version from the branch or download [lovelace-horizon-card.zip](https://github.com/rejuvenate/lovelace-horizon-card/files/11962341/lovelace-horizon-card.zip) (built from the branch).

**Comment by ildar170975** [comment]
@avataar 
I downloaded the zip file and copied js into community/lovelace-horizon-card.
Seems that styles are applied:

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/f10d863e-02a5-4ac7-961b-d444f93a318e)

**Comment by Opontios** [comment]
@ildar170975
How can the below be applied to the new version of the card?
Thanks

```
card_mod:
  style: |
    ha-card {
      --ha-card-background: transparent;
      box-shadow: none;
    }
```

**Comment by WarC0zes** [comment]
> @ildar170975 How can the below be applied to the new version of the card? Thanks
> 
> ```
> card_mod:
>   style: |
>     ha-card {
>       --ha-card-background: transparent;
>       box-shadow: none;
>     }
> ```
Hi,
like this:
```
type: custom:horizon-card
moon: true
fields:
  azimuth: true
  elevation: true
  moonrise: true
  moonset: true
  moon_phase: false
  time_format: 24
card_mod:
  style: |
    ha-card {
      --ha-card-background: transparent;
      box-shadow: none;
    }
```

**Comment by WarC0zes** [comment]
@Opontios 
> ```
> card_mod:
>   style: |
>     ha-card {
>       --ha-card-background: transparent;
>       box-shadow: none;
>     }
> ```

Hi, like this: 
```
type: custom:horizon-card
moon: true
fields:
  azimuth: true
  elevation: true
  moonrise: true
  moonset: true
  moon_phase: false
  time_format: 24
  card_mod:
    style: |
      ha-card {
        --ha-card-background: transparent;
        box-shadow: none;
     }
 ```

**Comment by WarC0zes** [comment]
@Opontios 
> 
> ```
> card_mod:
>   style: |
>     ha-card {
>       --ha-card-background: transparent;
>       box-shadow: none;
>     }
> ```
Hi,
like this:
```
type: custom:horizon-card
moon: true
fields:
  azimuth: true
  elevation: true
  moonrise: true
  moonset: true
  moon_phase: false
  time_format: 24
card_mod:
  style: |
    ha-card {
      --ha-card-background: transparent;
      box-shadow: none;
    }
```

**Comment by ildar170975** [comment]
@Opontios 
Another example:
![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/9af35016-db93-45a9-8148-13fa66b8b237)
```
type: custom:horizon-card
card_mod:
  style: |
    ha-card {
      --ha-card-background: red;
      box-shadow: 5px 5px 8px red, 10px 10px 8px green, 15px 15px 8px blue;
    }
```

**Comment by fredrikpersson92** [comment]
Has anyone been able to style the grey lines?
hc-lines in the web inspector

**Comment by WarC0zes** [comment]
> Has anyone been able to style the grey lines? hc-lines in the web inspector
here's for hc-lines:
```
            card_mod:
              style: |
                :host {
                  --hc-lines: yellow !important;
                }
```

**Comment by fredrikpersson92** [comment]
Legend! Thank you

**Comment by Schlicki** [comment]
May be I'm just a little blind, but as a newbie to the CSS with card-mod: How can I change the font and its size of the card? Size doesn't matter,  I know, but it shall match the target..... :D :D
