### ISSUE TITLE
Card shows AM/PM with EN locale regardless of settings

### ISSUE THREAD

**Issue by petrm** [rejuvenate/lovelace-horizon-card#44]
The original sun card respected my profile settings for 24h clock with English locale. Regardless if I set 12/24h clock in the profile settings or the card, I always get AM/PM. Changing the card to DE locale also changes the clock to 24h.
Am I missing something?

**Comment by avataar** [comment]
Try setting `use12hourClock: false` on the card:

```yaml
type: custom:horizon-card
use12hourClock: false
```

This issue will be resolved in a future version where the time format will obey Home Assistant's settings by default.

**Comment by petrm** [comment]
I have  use12hourClock: false set, sorry if this was not clear from the first post. It has no effect.

**Comment by petrm** [comment]
I see 24h clock when I explicitly select German in the card options. It only happens with EN as default locale.

**Comment by avataar** [comment]
> I have use12hourClock: false set, sorry if this was not clear from the first post. It has no effect.

I can confirm that setting this on the card makes the clock 24-hour regardless of the language settings (of HA or the card). I can also confirm it works like that in Chrome, Firefox and Safari. Using the latest v0.7.2.

Can you double check the casing of the key (i.e., use12hourClock and not use12HourClock or something)? If that's correct try a different browser too. Other than that I can't think of any reason for it not working for you.

**Comment by petrm** [comment]
Thanks for checking, PEBKAC.

I had use12hourClock under fields, sorry for the noise.
