### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by ThomDietrich** [rejuvenate/lovelace-horizon-card#48]
Hello friends.

In another issue we agreed to release a "symbolic" version 1.0. Let's agree on the steps forward:

- #42
- #47
- #45
- Currently blocking: https://github.com/hacs/default/pull/1808
- #43
- #33
- Release version 1.0 🎉 
- Major next development step: https://github.com/rejuvenate/lovelace-horizon-card/issues/40

Anything else in terms of bugs or improvement wishes before we are proud to release v1.0 ?

**Comment by JosefRypacek** [comment]
It would be fine to make it available in HACS!

**Comment by ThomDietrich** [comment]
We have no control over that, as we are waiting for https://github.com/hacs/default/pull/1808
In the meantime you can add the project as a custom repository, see the README.

**Comment by edwardtfn** [comment]
Done!

**Comment by jgverweij** [comment]
Note that any changes now postpone the introduction into HACS, as it is then pushed back to the end of the list.

**Comment by edwardtfn** [comment]
I haven't changed the PR itself, but just my comments with the links for the latest release and validations. This shouldn't affect the position in the queue.
