### ISSUE TITLE
Polymer Deprecated - Does this impact Horizon card?

### ISSUE THREAD

**Issue by CaptTom9** [rejuvenate/lovelace-horizon-card#49]
I was reading that Polymer is [deprecated in HA](https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/) and support for it is scheduled to be removed. I noticed some references to Polymer in the .js file. Will this impact the Horizon card?

**Comment by avataar** [comment]
Horizon card uses Lit. I guess the "Polymer" references are simply because of copyrights (Lit is related to Polymer). Horizon card is not impacted.
