### ISSUE TITLE
formatting

### ISSUE THREAD

**Issue by Mariusthvdb** [rejuvenate/lovelace-horizon-card#50]
thanks for rejuvenating! a much appreciated card, that can be given a future, and improvements, looking forward to that!.

Please let me ask.suggest something regarding formatting.
before I had set:
```
    card_mod:
      style: |
        .sun-card-header span {
         font-size: var(--mdc-typography-body1-font-size) !important;
         padding-bottom: 0px !important;
        }
        .sun-card-text-subtitle {
          color: var(--secondary-text-color) !important;
        }
        .sun-card-footer span {
          font-size: var(--mdc-typography-body1-font-size) !important;
        }
        .sun-card-footer-row {
          padding-top: 0px !important
        }
```

to get the top formatting (and have all fonts a bit more modest in the frontend)

<img width="507" alt="Scherm­afbeelding 2023-04-23 om 14 28 18" src="https://user-images.githubusercontent.com/33354141/233839907-e11beea3-c2f9-41dc-8245-deb3d819b262.png">

now I have copied that exact same card-mod to the new card, changed it to horizon-card:

```
    card_mod:
      style: |
        .horizon-card-header span {
         font-size: var(--mdc-typography-body1-font-size) !important;
         padding-bottom: 0px !important;
        }
        .horizon-card-text-subtitle {
          color: var(--secondary-text-color) !important;
        }
        .horizon-card-footer span {
          font-size: var(--mdc-typography-body1-font-size) !important;
        }
        .horizon-card-footer-row {
          padding-top: 0px !important
        }
```

but it does not apply, probably the elements are different now.

it  would however be a great feature, to have some formatting in the card config itself. Please consider adding that to the features?

also, it would be a nice gesture to us yaml users, to have a basic config with all option in the docs, so we can simply copy and paste. Why not add something like:

```
  - type: custom:horizon-card
    timeFormat: 24h
    fields:

#       sunrise: true
#       sunset: true
#       dawn: true
#       noon: true
#       dusk: true
      azimuth: true #false
      elevation: true #false
```

As a final remark for now:
note the text at 'zone-middag' (solar noon) in the original, and 'middag-uur' (midday our) in the new card. The latter seems incorrect, as it indicates the regular time name, and not the solar name.

This should probably be corrected in the translations.

 thanks and please keep up the good work!

**Comment by WarC0zes** [comment]
https://github.com/rejuvenate/lovelace-horizon-card/issues/30

**Comment by Mariusthvdb** [comment]
Dang, I missed that. Apologies.

Will close...
