### ISSUE TITLE
Error when adding to HACS

### ISSUE THREAD

**Issue by geidorei** [rejuvenate/lovelace-horizon-card#52]
I'm getting the following error when adding, any ideas?

<Integration rejuvenate/lovelace-horizon-card> Repository structure for v0.9.0 is not compliant

I've done a look on github, google etc but canty see a resolution.

**Comment by ThomDietrich** [comment]
According to the "repository structure" section in the docs above, we need to set `content_in_root` to true in hacs.json. Additionally a `manifest.json` is missing

**Comment by HrGaertner** [comment]
For me at least adding the repository as custom worked fine

**Comment by ThomDietrich** [comment]
Just had another look. The docs link posted by @metbril was for integrations, we are a plugin. As there were no other complains, I think we are good?
