### ISSUE TITLE
Adding to hacs default

### ISSUE THREAD

**Issue by HrGaertner** [rejuvenate/lovelace-horizon-card#53]
Hello,

i would like to see this in the hacs repository. May i add it? I will take care of the whole procedure if you would like that.

Thanks a lot in advance

**Comment by Tontze** [comment]
Personally i would love to see it in hacs :)

**Comment by ThomDietrich** [comment]
Already underway: https://github.com/rejuvenate/lovelace-horizon-card/issues/48#issuecomment-1515827235
