### ISSUE TITLE
Not seeing information on the Sunrise, Sunset, Dawn and Dusk

### ISSUE THREAD

**Issue by MTijn** [rejuvenate/lovelace-horizon-card#73]
Since I have updated to v1.0 of the card I am not able to show the Sunrise, Sunset, Dawn and Dusk information any more. They've been replaced with dashes, as if there is no information on them any more. When I switch the card back to v0.9.1 I do see this information again.

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/3725681/a47d49a4-0d5d-49d6-84b3-50087b2ba5be)
This is how it looks to me, and this is the configuration I use
![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/3725681/bf35fefd-88fa-4cda-a059-05963a8a8f2a)

- Version of the card used v1.0.0
- HA version 2023.7.2

Cache is off by default
![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/3725681/5b3df520-7d5b-495b-b95c-918f6cf43f5f)

Is there any way for me to correct this?

**Comment by avataar** [comment]
The graph and the lack of sunrise/sunset times indicates a very northern latitude, where the Sun doesn't go below the horizon at this time of the year.

If this is supposed to be Almere in the Netherlands, that isn't sufficiently northern for what you see. Check the location set on your Home Assistant. If that is indeed set to where Almere is, then it should work.

You can also set an alternative location just for the card by adding this to the card config (coordinates for Almere):
```yaml
latitude: 52.37495
longitude: 5.2196
```

**Comment by jeroenm2** [comment]
Hi @avataar,

It seems that the issue is caused by a negative elevation, welcome to the Netherlands :).
When I set it to zero the values do show

**Comment by Schaduwval** [comment]
Hello,

will this bug be fixed in a future release?

**Comment by ThomDietrich** [comment]
Consolidating to avoid fragmentation — this looks like the same topic as #101, which we're keeping as the tracker. Please follow along and add details there. (Closing as duplicate; reopen if you think it's distinct.)
