### ISSUE TITLE
Moon phase presentation

### ISSUE THREAD

**Issue by jm314159** [rejuvenate/lovelace-horizon-card#74]
Hi!
Not sure if it is an issue, perhaps a misconfiguration or misunderstanding on my side. Please advise on these two cases.

First - I can see that the crescent on the graph rotates following the Sun. With some specific terms, like when having set manually
`now: 2023-07-21T12:52:30+0000`
the Sun and Moon are on the same elevation. I think, the crescent should be directed toward 0 degrees (if we consider co-ordinate system). Meanwhile, it is above zero, like on this picture:
![obraz](https://github.com/rejuvenate/lovelace-horizon-card/assets/110235880/932098a7-9740-4a0f-88b1-83ffcef6d882)
Is it related to the logarithmic scale of the Moon elevation perhaps?

Second - With moon_phase_rotation unset, the icon should rotate to match the approximate view for the configured latitude. I did not enforce that setting. However, in my case, the icon does not change at all. Please compare the former picture to the following one obtained for
`now: 2023-07-21T19:52:30+0000`
![obraz](https://github.com/rejuvenate/lovelace-horizon-card/assets/110235880/c673e808-6c02-4882-aad4-82301b07a77f)

How is it possible to get the blue icon rotated?

Best regards,
Jurek

**Comment by avataar** [comment]
The icon that moves along the graph path is rotated freely to show the actual view of the Moon at that given moment (i.e., what you would see in the sky if the Moon is visible). The angle changes as the Moon travels along its path. The logarithmic scale has nothing to do with it (it has to do with how high above or below the icon is drawn).

The icon that shows the Moon phase is rotated statically based only on the latitude of the configured location and is just a close approximation of what that phase would look like when it's high above the horizon (just like on your first screenshot where both icons share their rotation angle). Traditionally, such icons aren't rotated and represent the view from very northern (crescent growing right-to-left) or very southern latitudes (crescent growing left-to-right). I didn't want to bias it by choosing either so I made it depend on the latitude and thereby provide an icon that is localized to your particular location.

I hope this makes it clearer.

**Comment by jm314159** [comment]
Thank you for a detailed answer! All's clear to me now.
