### ISSUE TITLE
Any way to make the card more compact?

### ISSUE THREAD

**Issue by alexruffell** [rejuvenate/lovelace-horizon-card#99]
Thank you for rejuvenating ;)  the card! Is there any way to make it more compact?

I can use card_mod if need be, but any tips on what elements to shrink would be great as I don't have a full understanding on the layout so I go on endless hunts for code examples until I find something that works :S

**Comment by ildar170975** [comment]
You may use this as a starting point.

**Comment by alexruffell** [comment]
@ildar170975 How could I possibly forget about that epic thread you created! That worked 100%, smaller and looks better too on my dashboard.
